# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
R: bioc-devel
r_github_packages: theislab/kBET
dist: trusty 
os:
  - linux
  - osx