# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
R:
  - devel
  - bioc-devel
dist: trusty
os:
  - linux
  - osx
after_success:
    - Rscript -e 'covr::codecov()'
env:
  - TRAVIS_R_VERSION = "3.6.0"