# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R

sudo: false

cache: packages

R:
  - bioc-devel
  
dist: trusty

os:
  - linux
  - osx

script: 
  - R -e 'install.packages("BiocManager")'
  - R -e 'BiocManager::install(version = "3.9")'  

  
r_github_packages:
  - r-lib/covr

after_success:
  - Rscript -e 'covr::codecov()'