# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

eigenMatMult <- function(A, B) {
    .Call('_scMerge_eigenMatMult', PACKAGE = 'scMerge', A, B)
}

eigenMatInverse <- function(A) {
    .Call('_scMerge_eigenMatInverse', PACKAGE = 'scMerge', A)
}

