# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title fast matrix multiplication
#' @param A a matrix
#' @param B a matrix
#' @export
eigenMatMult <- function(A, B) {
    .Call('_scMerge_eigenMatMult', PACKAGE = 'scMerge', A, B)
}

#' @title fast matrix inverse
#' @param A a matrix
#' @export
eigenMatInverse <- function(A) {
    .Call('_scMerge_eigenMatInverse', PACKAGE = 'scMerge', A)
}

#' @title fast matrix inverse
#' @param A a matrix
#' @param B a matrix
#' @export
eigenResidop <- function(A, B) {
    .Call('_scMerge_eigenResidop', PACKAGE = 'scMerge', A, B)
}

#' residop
#'
#' @usage residop(A, B)
#' @param A The first matrix
#' @param B The second matrix
#' @return The result
#' @export
residop <- function(A, B) {
    .Call('_scMerge_residop', PACKAGE = 'scMerge', A, B)
}

