# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Fast matrix multiplication using RcppEigen
#' @param A a matrix
#' @param B a matrix
#' @export
#' @return The matrix product of A times B
#' @examples
#' A = matrix(0, ncol = 500, nrow = 500)
#' system.time(A %*% A)
#' system.time(eigenMatMult(A, A))
eigenMatMult <- function(A, B) {
    .Call(`_scMerge_eigenMatMult`, A, B)
}

#' @title fast matrix residual operator using RcppEigen
#' @param A a matrix
#' @param B a matrix
#' @export
#' @return The matrix product of
#' \deqn{A - B(B^t B)^{-1} B^t A}
#' @examples
#' Y = M = diag(1, 500)
#' system.time(scMerge::eigenResidop(Y, M))
#' system.time(ruv::residop(Y, M))
eigenResidop <- function(A, B) {
    .Call(`_scMerge_eigenResidop`, A, B)
}

