on:
  push:
    branches: master

name: trigger-scmerge-docker
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.SCMERGE_DOCKER_TOKEN }}
          repository: kevinwang09/scmerge_docker ## GitHub Repo to be triggered
          event-type: auto-docker-build ## Must match the event-type in the receiver actions
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
